#!/bin/bash

# Check if fzf is installed
if ! command -v fzf &> /dev/null; then
    echo "fzf is not installed. Please install fzf to use this script."
    exit 1
fi

# Ensure the EDITOR environment variable is set
if [ -z "$EDITOR" ]; then
    echo "EDITOR environment variable is not set. Please set it to your preferred text editor."
    exit 1
fi
ink list | fzf --preview 'bat --color=always {2}' --preview-window '~3' --with-nth=1 --delimiter='\t' | cut -f2 | sed 's/.*/"&"/' | xargs -o $EDITOR
